import Foundation

struct SentenceCorpus {
    static let genericSentences: [String] = [
        "The sun rises in the east and sets in the west.",
        "A gentle breeze rustled the leaves of the old oak tree.",
        "She walked along the beach, collecting seashells.",
        "The mountains stood tall against the blue sky.",
        "He read a book by the fireplace on a cold winter night.",
        "The cat slept peacefully on the windowsill.",
        "Birds chirped happily in the garden.",
        "The aroma of fresh coffee filled the kitchen.",
        "They hiked up the trail to see the waterfall.",
        "The city lights twinkled like stars in the distance.",
        "A heavy rain began to fall, tapping on the roof.",
        "She painted a beautiful landscape with watercolors.",
        "The dog chased the ball across the park.",
        "He played the guitar with great passion.",
        "The stars shone brightly in the clear night sky.",
        "They enjoyed a picnic in the meadow.",
        "The train rattled down the tracks.",
        "She wrote a letter to her friend across the ocean.",
        "The old house had a mysterious charm.",
        "He fixed the broken fence in the backyard.",
        "The flowers bloomed in vibrant colors.",
        "A butterfly landed on her shoulder.",
        "They danced under the moonlight.",
        "The waves crashed against the rocky shore.",
        "She baked a delicious apple pie.",
        "He drove his car down the winding road.",
        "The clock ticked loudly in the silent room.",
        "They built a sandcastle on the beach.",
        "The wind howled through the trees during the storm.",
        "She knitted a warm scarf for winter.",
        "He studied hard for his upcoming exam.",
        "The children laughed and played in the playground.",
        "The river flowed gently downstream.",
        "She watched the sunset paint the sky orange and purple.",
        "He found an old coin in the attic.",
        "The library was filled with the smell of old books.",
        "They went for a bike ride on a sunny afternoon.",
        "The snow covered the ground in a white blanket.",
        "She sang a lullaby to put the baby to sleep.",
        "He carved a wooden figure with a small knife.",
        "The bakery sold fresh bread every morning.",
        "They visited a museum to learn about history.",
        "The forest was dense and full of wildlife.",
        "She practiced yoga in the park.",
        "He captured a beautiful photo of the landscape.",
        "The candle flickered in the drafty room.",
        "They watched a movie together on Friday night.",
        "The ice cream melted quickly in the heat.",
        "She organized her desk for better productivity.",
        "He helped his neighbor carry the groceries.",
        "The clouds drifted lazily across the sky.",
        "They planned a trip to the mountains.",
        "The music played softly in the background.",
        "She planted a vegetable garden in her backyard.",
        "He repaired the leaky faucet in the kitchen.",
        "The leaves turned gold and red in the autumn.",
        "They sat on the porch and drank lemonade.",
        "The fire crackled and popped in the hearth.",
        "She learned to play the piano at a young age.",
        "He went fishing by the lake early in the morning.",
        "The traffic was heavy during rush hour.",
        "They celebrated their anniversary with a nice dinner.",
        "The moon cast a silver glow over the lake.",
        "She wrote a poem about nature.",
        "He built a birdhouse for the garden.",
        "The waves were perfect for surfing today.",
        "They explored the ancient ruins.",
        "The smell of rain on dry earth is distinct.",
        "She took a long nap on the hammock.",
        "He detailed his car on the weekend.",
        "The stars are actually distant suns.",
        "They volunteer at the local shelter.",
        "The old bridge crossed the narrow river.",
        "She keeps a diary of her daily thoughts.",
        "He runs five miles every morning.",
        "The theater was packed for the premiere.",
        "They collected firewood for the campfire.",
        "The owl hooted in the distance.",
        "She loves to cook italian food.",
        "He solved the crossword puzzle quickly.",
        "The dew sparkled on the grass in the morning.",
        "They watched the fireworks display.",
        "The cat chased a laser pointer around the room.",
        "She bought a new dress for the party.",
        "He learned to speak Spanish fluently.",
        "The garden is full of blooming roses.",
        "They went camping in the national park.",
        "The tea was too hot to drink.",
        "She sketches in her notebook during breaks.",
        "He plays basketball with his friends.",
        "The rainbow appeared after the storm.",
        "They visited the zoo to see the pandas.",
        "The old photograph brought back memories.",
        "She enjoys reading mystery novels.",
        "He works as a software engineer.",
        "The beach was crowded on the hot day.",
        "They went for a swim in the pool.",
        "The snow melted as spring arrived.",
        "She dreams of traveling the world.",
        "He plays chess with his grandfather.",
        "The soup was warm and comforting.",
        "They decorated the house for the holidays.",
        "The bird built a nest in the tree.",
        "She attends a pottery class on Tuesdays.",
        "He enjoys hiking in the wilderness.",
        "The city never sleeps.",
        "They watched the parade from the balcony.",
        "The lighthouse guided ships to safety.",
        "She keeps a garden of herbs.",
        "He rides his motorcycle on weekends.",
        "The thunder rolled across the valley.",
        "They played board games all night.",
        "The horse galloped across the field.",
        "She likes to watch documentaries.",
        "He paints landscapes in oil.",
        "The river is deep and wide.",
        "They went to the market to buy fresh fruit.",
        "The fog covered the city in the morning.",
        "She enjoys walking in the rain.",
        "He collects vintage records.",
        "The tree provided shade on a sunny day.",
        "They sat by the campfire and told stories.",
        "The wind blew the kite high in the sky.",
        "She practices meditation daily.",
        "He enjoys woodworking in his garage.",
        "The mountains are covered in snow.",
        "They went for a boat ride on the lake.",
        "The coffee shop was bustling with activity.",
        "She writes short stories in her free time.",
        "He plays the drums in a band.",
        "The flowers smell sweet in the spring.",
        "They went to a concert last night.",
        "The old car still runs well.",
        "She enjoys gardening on weekends.",
        "He likes to go for long drives.",
        "The sunset was breathtaking.",
        "They had a picnic in the park.",
        "The rain washed away the dust.",
        "She reads a book every week.",
        "He enjoys playing video games.",
        "The stars were bright last night.",
        "They went for a walk on the beach.",
        "The food was delicious.",
        "She likes to bake cookies.",
        "He plays soccer on Saturdays.",
        "The weather is perfect today.",
        "They went to the movies.",
        "The dog is very friendly.",
        "She has a beautiful voice.",
        "He is a talented artist.",
        "The house is very old.",
        "They are best friends.",
        "The car is fast.",
        "She is very smart.",
        "He is hard working.",
        "The book is interesting.",
        "They are happy.",
        "The movie was funny.",
        "She is kind.",
        "He is strong.",
        "The game was exciting.",
        "They are traveling.",
        "The music is loud.",
        "She is dancing.",
        "He is running.",
        "The food is hot.",
        "They are eating.",
        "The water is cold.",
        "She is swimming.",
        "He is sleeping.",
        "The sun is shining.",
        "They are laughing.",
        "The sky is blue.",
        "She is smiling.",
        "He is talking.",
        "The flowers are blooming.",
        "They are walking.",
        "The birds are singing.",
        "She is listening.",
        "He is writing.",
        "The wind is blowing.",
        "They are playing.",
        "The fire is burning.",
        "She is cooking.",
        "He is driving.",
        "The rain is falling.",
        "They are watching.",
        "The snow is white.",
        "She is reading.",
        "He is working.",
        "The night is dark.",
        "They are dreaming.",
        "The day is long.",
        "She is learning.",
        "He is teaching.",
        "The world is big.",
        "They are exploring.",
        "The life is beautiful.",
        "She is loving.",
        "He is living.",
        "The time is now.",
        "They are together.",
        "The love is forever.",
        "She is happy.",
        "He is peaceful.",
        "The joy is real.",
        "They are free.",
        "The peace is here.",
        "She is grateful.",
        "He is hopeful.",
        "The faith is strong.",
        "They are blessed.",
        "The hope is alive.",
        "She is inspired.",
        "He is creative.",
        "The art is expression.",
        "They are creating.",
        "The beauty is everywhere.",
        "She is seeing.",
        "He is feeling.",
        "The touch is gentle.",
        "They are hugging.",
        "The kiss is sweet.",
        "She is whispering.",
        "He is listening.",
        "The silence is golden.",
        "They are quiet.",
        "The noise is gone.",
        "She is resting.",
        "He is relaxing.",
        "The calm is restoring.",
        "They are refreshing.",
        "The energy is renewed.",
        "She is active.",
        "He is moving.",
        "The action is taken.",
        "They are doing.",
        "The result is good.",
        "She is succeeding.",
        "He is winning.",
        "The victory is theirs.",
        "They are celebrating.",
        "The party is fun.",
        "She is dancing.",
        "He is singing.",
        "The music is playing.",
        "They are joyful.",
        "The happiness is shared.",
        "She is giving.",
        "He is receiving.",
        "The gift is love.",
        "They are thankful.",
        "The gratitude is felt.",
        "She is smiling.",
        "He is laughing.",
        "The laughter is contagious.",
        "They are happy.",
        "Discovery is a journey not a destination.",
        "Kindness costs nothing but means everything.",
        "Patience is a virtue worth cultivating.",
        "Wisdom comes from experience and reflection.",
        "Courage is facing fear, not the absence of it.",
        "Integrity is doing the right thing when no one is watching.",
        "Humility is strength under control.",
        "Compassion serves to heal the world.",
        "Empathy connects us to one another.",
        "Forgiveness sets the prisoner free.",
        "Hope acts as an anchor for the soul.",
        "Love is the greatest of all virtues.",
        "Truth remains the foundation of trust.",
        "Justice ensures fairness for everyone.",
        "Freedom represents the power to choose.",
        "Responsibility brings meaning to life.",
        "Discipline creates freedom in the long run.",
        "Perseverance leads to eventual success.",
        "Excellence is a habit, not an act.",
        "Creativity solves problems in new ways.",
        "Innovation drives progress forward.",
        "Collaboration achieves more than isolation.",
        "Leadership inspires others to dream more.",
        "Service is the rent we pay for living.",
        "Gratitude turns what we have into enough.",
        "Contentment is wealth of the mind.",
        "Simplicity clears the path to clarity.",
        "Balance is the key to a healthy life.",
        "Nature heals the weary spirit.",
        "Silence speaks when words fail.",
        "Listen more than you speak.",
        "Learn something new every day.",
        "Teach what you know to others.",
        "Share your blessings with the world.",
        "Give without expecting return.",
        "Receive with an open heart.",
        "Grow through challenges and change.",
        "Adapt to the seasons of life.",
        "Flow like water around obstacles.",
        "Stand tall like a mountain in storms.",
        "Shine like a star in the darkness.",
        "Burn bright like a fire within.",
        "Cool down like a gentle breeze.",
        "Refresh yourself like morning dew.",
        "Ground yourself like deep roots.",
        "Reach high like the branches.",
        "Bloom where you are planted.",
        "Sow seeds of kindness daily.",
        "Harvest the fruits of your labor.",
        "Nurture your dreams with action.",
        "Protect your peace of mind.",
        "Defend the weak and vulnerable.",
        "Speak up for those without a voice.",
        "Stand for what is right.",
        "Walk the path of righteousness.",
        "Run the race with endurance.",
        "Fight the good fight of faith.",
        "Finish the course with joy.",
        "Rest in the assurance of love.",
        "Believe in the impossible.",
        "Imagine a better world.",
        "Create the future you desire.",
        "Build bridges, not walls.",
        "Open doors of opportunity.",
        "Close chapters of the past.",
        "Write your own story.",
        "Sing your primitive song.",
        "Dance to your own rhythm.",
        "Paint your life with color.",
        "Sculpt your character with care.",
        "Design your destiny with purpose.",
        "Engineer a life of value.",
        "Calculate the cost of choices.",
        "Measure twice, cut once.",
        "Plan your work, work your plan.",
        "Execute with precision.",
        "Evaluate your results honestly.",
        "Improve continuously.",
        "Innovate constantly.",
        "Inspect what you expect.",
        "Invest in yourself.",
        "Save for a rainy day.",
        "Spend wisely on what matters.",
        "Give generously to causes.",
        "Help others succeed.",
        "Lift others up.",
        "Encourage the discouraged.",
        "Comfort the brokenhearted.",
        "Heal the sick.",
        "Feed the hungry.",
        "Clothe the naked.",
        "House the homeless.",
        "Welcome the stranger.",
        "Love your neighbor.",
        "Respect your elders.",
        "Honor your parents.",
        "Cherish your children.",
        "Value your friends.",
        "Appreciate your partner.",
        "Respect yourself.",
        "Be true to who you are.",
        "Live authentically.",
        "Speak truth to power.",
        "Seek justice.",
        "Love mercy.",
        "Walk humbly.",
        "Pray without ceasing.",
        "Meditate day and night.",
        "Focus on the good.",
        "Think positive thoughts.",
        "Speak life.",
        "Act with love.",
        "Be the change.",
        "Light the way.",
        "Show the way.",
        "Lead the way.",
        "Make a difference.",
        "Leave a legacy.",
        "Impact the world.",
        "Change lives.",
        "Save souls.",
        "Redeem the time.",
        "Seize the day.",
        "Live in the moment.",
        "Enjoy the journey.",
        "Trust the process.",
        "Believe in yourself.",
        "Have faith.",
        "Keep hope alive.",
        "Love never fails.",
        "Peace be with you."
    ]
}
